#model_name_or_path: "BAAI/Bunny-v1_0-3B"
model_name_or_path: "BAAI/Bunny-Llama-3-8B-V"
beta: 0.1 # DPO beta value
# output_dir: null  # to be set by the script
bf16: true
fix_vit: true
num_train_epochs: 2
# per_device_train_batch_size: 4
# per_device_eval_batch_size: 4
# gradient_accumulation_steps: 8
per_device_train_batch_size: 2
per_device_eval_batch_size: 2
gradient_accumulation_steps: 16
# evaluation_strategy: "epoch"
save_strategy: "epoch" # if save_strategy is used the checkpoint will be saved after each epoch and save_steps will be ignored
# save_steps: 50  # interval at which checkpoint will be saved
save_total_limit: 1
learning_rate: 0.00001
weight_decay: 0.05
adam_beta2: 0.98
warmup_ratio: 0.1
lr_scheduler_type: "cosine"
logging_steps: 10  # interval at which metrics will be displayed 
report_to: wandb
#model_max_length: 2048
model_max_length: 1280
gradient_checkpointing: true
use_lora: true
#q_lora: false
q_lora: true
bf16: true
tf32: true
logging_first_step: true
remove_unused_columns: false
lora_r: 64  
lora_alpha: 128 
# lora_r: 16
# lora_alpha: 32 
lora_target_modules: all-linear 
dataset_path: ./data/vlfeedback_llava_10k_gen.json # preference dataset path
run_name: mdpo_bunny_sd_all_attr_sb_8b
output_dir: ./checkpoint/mdpo_bunny_sd_all_attr_sb_8b # directory where checkpoints and outputs will be saved